# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_id', models.CharField(default=b'611c1afe93cd11e88df8309c23b2855c', max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('poigenre', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('ucode', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('del_sign', models.CharField(default='N', max_length=5, verbose_name='\u5220\u9664\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(default=b'611c1aff93cd11e88df8309c23b2855c', max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('ucode', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('del_sign', models.CharField(default='N', max_length=5, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.Poi')),
                ('sur_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poi.Review')),
            ],
        ),
    ]
